#UAT DB
POSTGRES_SQL_USERNAME: paymentgatewaydb
POSTGRES_SQL_PASSWORD: paymentproccessor#4321
POSTGRES_SQL_HOST: 10.1.177.129
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: authentication

#Server
SERVER_PORT: 9095
ACTIVE_PROFILE: uat